# Copyright 2020, Data61, CSIRO (ABN 41 687 119 230)
#
# SPDX-License-Identifier: BSD-2-Clause

# Actions to run on pull requests

name: PR

on: [pull_request]

jobs:
  gitlint:
    name: Gitlint
    runs-on: ubuntu-latest
    steps:
    - uses: seL4/ci-actions/gitlint@master
      with:
        token: ${{ secrets.READ_TOKEN }}

  whitespace:
    name: 'Trailing Whitespace'
    runs-on: ubuntu-latest
    steps:
    - uses: seL4/ci-actions/git-diff-check@master
      with:
        token: ${{ secrets.READ_TOKEN }}

  shell:
    name: 'Portable Shell'
    runs-on: ubuntu-latest
    steps:
    - uses: seL4/ci-actions/bashisms@master
      with:
        token: ${{ secrets.READ_TOKEN }}

  style:
    name: Style
    runs-on: ubuntu-latest
    steps:
    - uses: seL4/ci-actions/style@master
      with:
        token: ${{ secrets.READ_TOKEN }}

  thylint:
    name: 'Theory Linter'
    runs-on: ubuntu-latest
    steps:
    - uses: seL4/ci-actions/thylint@master
      with:
        token: ${{ secrets.READ_TOKEN }}
    - uses: yuzutech/annotations-action@v0.4.0
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        title: 'File annotations for theory linter'
        input: './annotations.json'
      continue-on-error: true
      if: always()
